-- PremiseFlow :: 03_core_tables.sql
-- Assumptions as first-class governed objects.

USE DATABASE PREMISEFLOW;

-- ---------------------------------------------------------------------------
-- Assumption registry
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CORE.ASSUMPTIONS (
  ASSUMPTION_ID    STRING NOT NULL,
  NAME             STRING,
  STATEMENT        STRING,
  DOMAIN           STRING,        -- LIQUIDITY | IRRBB | CREDIT | CAPITAL | OPERATIONAL
  OWNER_ROLE       STRING,
  MATERIALITY      STRING,        -- CRITICAL | HIGH | MEDIUM | LOW
  STATUS           STRING,        -- VALID|WATCH|CHALLENGED|UNDER_REVIEW|BREACHED|RETIRED
  CURRENT_VERSION  NUMBER(6,0),
  METRIC_CODE      STRING,
  LAST_VALIDATED_AT TIMESTAMP_NTZ,
  CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Immutable version history. Approved versions are never overwritten.
CREATE TABLE IF NOT EXISTS CORE.ASSUMPTION_VERSIONS (
  VERSION_ID        STRING NOT NULL,
  ASSUMPTION_ID     STRING NOT NULL,
  VERSION_NUMBER    NUMBER(6,0),
  STATEMENT         STRING,
  EXPECTED_VALUE    FLOAT,
  LOWER_BOUND       FLOAT,
  UPPER_BOUND       FLOAT,
  CHALLENGE_THRESHOLD FLOAT,
  BREACH_THRESHOLD    FLOAT,
  PERSISTENCE_DAYS    NUMBER(6,0),
  DIRECTION           STRING,     -- LOWER_IS_WORSE | UPPER_IS_WORSE | TWO_SIDED
  VALID_FROM        TIMESTAMP_NTZ,
  VALID_TO          TIMESTAMP_NTZ,
  VALIDITY_ENVELOPE VARIANT,
  EVIDENCE_SUMMARY  STRING,
  APPROVAL_STATUS   STRING,       -- DRAFT | PROPOSED | APPROVED | REJECTED | SUPERSEDED
  APPROVED_BY       STRING,
  APPROVED_AT       TIMESTAMP_NTZ,
  PROPOSED_BY       STRING,
  PROPOSED_AT       TIMESTAMP_NTZ,
  SUPERSEDES_VERSION_ID STRING,
  IS_CURRENT        BOOLEAN DEFAULT FALSE,
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CORE.ASSUMPTION_EVIDENCE (
  EVIDENCE_ID     STRING NOT NULL,
  ASSUMPTION_ID   STRING,
  VERSION_ID      STRING,
  EVIDENCE_TYPE   STRING,   -- STRUCTURED_DATA | DOCUMENT | MODEL_RESULT | EXPERT_JUDGEMENT | OBSERVATION
  SOURCE_REF      STRING,
  SOURCE_DOCUMENT STRING,
  OBSERVED_VALUE  FLOAT,
  SAMPLE_SIZE     NUMBER(12,0),
  PERIOD_START    DATE,
  PERIOD_END      DATE,
  SUMMARY         STRING,
  CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Logical lineage: assumption -> models/metrics/reports/decisions/calcs/policies
CREATE TABLE IF NOT EXISTS CORE.ASSUMPTION_DEPENDENCIES (
  DEPENDENCY_ID     STRING NOT NULL,
  SOURCE_OBJECT     STRING NOT NULL,
  SOURCE_TYPE       STRING NOT NULL,   -- ASSUMPTION | MODEL | METRIC | REPORT | DECISION | CALCULATION | POLICY
  TARGET_OBJECT     STRING NOT NULL,
  TARGET_TYPE       STRING NOT NULL,
  RELATIONSHIP_TYPE STRING,            -- FEEDS | CONSTRAINS | JUSTIFIES | INPUT_TO
  MATERIALITY       STRING,            -- CRITICAL | HIGH | MEDIUM | LOW
  SENSITIVITY_NOTE  STRING,
  VALID_FROM        TIMESTAMP_NTZ,
  VALID_TO          TIMESTAMP_NTZ,
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Reality observations produced by the observation layer.
CREATE TABLE IF NOT EXISTS CORE.ASSUMPTION_OBSERVATIONS (
  OBSERVATION_ID   STRING NOT NULL,
  ASSUMPTION_ID    STRING NOT NULL,
  VERSION_ID       STRING,
  OBSERVATION_DATE DATE NOT NULL,
  METRIC_CODE      STRING,
  OBSERVED_VALUE   FLOAT,
  SAMPLE_SIZE      NUMBER(12,0),
  WINDOW_DAYS      NUMBER(6,0),
  CONTEXT          VARIANT,
  SOURCE           STRING,
  CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CORE.ASSUMPTION_CHALLENGES (
  CHALLENGE_ID      STRING NOT NULL,
  RUN_ID            STRING,
  ASSUMPTION_ID     STRING NOT NULL,
  VERSION_ID        STRING,
  EVALUATED_AT      TIMESTAMP_NTZ,
  OBSERVATION_DATE  DATE,
  OBSERVED_VALUE    FLOAT,
  EXPECTED_VALUE    FLOAT,
  DEVIATION         FLOAT,
  DEVIATION_PCT     FLOAT,
  PERSISTENCE_DAYS  NUMBER(6,0),
  CONFIDENCE        FLOAT,
  ROBUST_Z          FLOAT,
  CHANGE_POINT_DATE DATE,
  AFFECTED_SEGMENTS VARIANT,
  EVIDENCE_IDS      VARIANT,
  STATUS            STRING,   -- VALID|WATCH|CHALLENGED|BREACHED
  METHOD            STRING,
  EXPLANATION       STRING,
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CORE.ASSUMPTION_BREACHES (
  BREACH_ID         STRING NOT NULL,
  ASSUMPTION_ID     STRING NOT NULL,
  VERSION_ID        STRING,
  CHALLENGE_ID      STRING,
  DETECTED_AT       TIMESTAMP_NTZ,
  FIRST_BREACH_DATE DATE,
  OBSERVED_VALUE    FLOAT,
  EXPECTED_VALUE    FLOAT,
  PERSISTENCE_DAYS  NUMBER(6,0),
  SEVERITY          STRING,
  CONFIRMATION_STATUS STRING,   -- PENDING_HUMAN_CONFIRMATION | CONFIRMED | DISMISSED
  CONFIRMED_BY      STRING,
  CONFIRMED_AT      TIMESTAMP_NTZ,
  ROOT_CAUSE_SUMMARY STRING,
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ---------------------------------------------------------------------------
-- Downstream governed objects
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CORE.MODELS (
  MODEL_ID        STRING NOT NULL,
  NAME            STRING,
  MODEL_TYPE      STRING,
  OWNER_ROLE      STRING,
  TIER            STRING,
  LAST_VALIDATED  DATE,
  STATUS          STRING,
  DESCRIPTION     STRING
);

CREATE TABLE IF NOT EXISTS CORE.RISK_METRICS (
  METRIC_ID       STRING NOT NULL,
  NAME            STRING,
  METRIC_TYPE     STRING,
  UNIT            STRING,
  INTERNAL_LIMIT  FLOAT,
  REGULATORY_MIN  FLOAT,
  OWNER_ROLE      STRING,
  DESCRIPTION     STRING
);

CREATE TABLE IF NOT EXISTS CORE.DECISIONS (
  DECISION_ID       STRING NOT NULL,
  DECISION_REF      STRING,
  TITLE             STRING,
  COMMITTEE         STRING,
  DECISION_DATE     DATE,
  DECISION_TEXT     STRING,
  RATIONALE         STRING,
  APPROVED_BY       STRING,
  MATERIALITY       STRING,
  GOVERNANCE_STATUS STRING,   -- APPROVED | REASSESSMENT_REQUIRED | REAFFIRMED | SUPERSEDED
  STATUS_CHANGED_AT TIMESTAMP_NTZ,
  SOURCE_DOCUMENT   STRING,
  CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Records exactly which assumption VERSION a decision relied upon.
CREATE TABLE IF NOT EXISTS CORE.DECISION_DEPENDENCIES (
  DECISION_DEP_ID     STRING NOT NULL,
  DECISION_ID         STRING NOT NULL,
  ASSUMPTION_ID       STRING NOT NULL,
  VERSION_ID          STRING NOT NULL,
  RELIANCE_STRENGTH   STRING,   -- MATERIAL | SUPPORTING | CONTEXTUAL
  RELIANCE_NOTE       STRING,
  CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CORE.REASSESSMENTS (
  REASSESSMENT_ID     STRING NOT NULL,
  DECISION_ID         STRING,
  ASSUMPTION_ID       STRING,
  BREACH_ID           STRING,
  TRIGGERED_AT        TIMESTAMP_NTZ,
  TRIGGER_REASON      STRING,
  ORIGINAL_VERSION_ID STRING,
  OBSERVED_VALUE      FLOAT,
  APPROVED_VALUE      FLOAT,
  IMPACT_SUMMARY      STRING,
  MATERIALITY         STRING,
  AI_RECOMMENDATION   STRING,
  STATUS              STRING,   -- OPEN | IN_REVIEW | RESOLVED | DISMISSED
  RESOLVED_BY         STRING,
  RESOLVED_AT         TIMESTAMP_NTZ,
  RESOLUTION_NOTE     STRING,
  CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ---------------------------------------------------------------------------
-- Scenario / impact simulation
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS CORE.SCENARIOS (
  SCENARIO_ID     STRING NOT NULL,
  RUN_ID          STRING,
  ASSUMPTION_ID   STRING,
  SCENARIO_TYPE   STRING,   -- BASELINE | OBSERVED_BEHAVIOUR | PROPOSED_ASSUMPTION | USER_DEFINED
  NAME            STRING,
  RETENTION_INPUT FLOAT,
  INPUTS          VARIANT,
  CREATED_BY      STRING,
  CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CORE.SCENARIO_RESULTS (
  RESULT_ID       STRING NOT NULL,
  SCENARIO_ID     STRING NOT NULL,
  METRIC_ID       STRING,
  METRIC_NAME     STRING,
  METRIC_VALUE    FLOAT,
  UNIT            STRING,
  FORMULA         STRING,
  INPUTS          VARIANT,
  BREACHES_LIMIT  BOOLEAN,
  POC_DISCLAIMER  STRING DEFAULT 'Hackathon POC - illustrative simplified risk calculation.',
  CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- LCR / balance-sheet inputs for the simplified simulator.
CREATE TABLE IF NOT EXISTS CORE.LIQUIDITY_INPUTS (
  AS_OF_DATE                 DATE,
  HQLA_AMOUNT                FLOAT,
  RETAIL_STABLE_DEPOSITS     FLOAT,
  RETAIL_LESS_STABLE_DEPOSITS FLOAT,
  WHOLESALE_FUNDING          FLOAT,
  OTHER_OUTFLOWS             FLOAT,
  EXPECTED_INFLOWS           FLOAT,
  STABLE_RUNOFF_RATE         FLOAT,
  LESS_STABLE_RUNOFF_RATE    FLOAT,
  WHOLESALE_RUNOFF_RATE      FLOAT,
  AVG_FUNDING_COST_PCT       FLOAT,
  REPLACEMENT_FUNDING_SPREAD_BPS FLOAT,
  NOTES                      STRING
);

-- Outbox used when an external system (Jira/Slack) is not wired up.
CREATE TABLE IF NOT EXISTS CORE.ACTION_OUTBOX (
  ACTION_ID     STRING NOT NULL,
  ACTION_TYPE   STRING,
  TARGET_SYSTEM STRING,
  PAYLOAD       VARIANT,
  STATUS        STRING,   -- PENDING | SENT | FAILED | SKIPPED
  CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PROCESSED_AT  TIMESTAMP_NTZ,
  EXTERNAL_ID   STRING,
  DEDUPE_KEY    STRING,
  LAST_ERROR    STRING
);

SELECT 'CORE tables ready' AS STATUS;
