-- PremiseFlow :: 04_audit_tables.sql
-- Append-only audit substrate. Nothing important happens without an event.

USE DATABASE PREMISEFLOW;

CREATE TABLE IF NOT EXISTS AUDIT.AUDIT_EVENTS (
  EVENT_ID           STRING NOT NULL,
  EVENT_TYPE         STRING NOT NULL,
  OBJECT_TYPE        STRING,
  OBJECT_ID          STRING,
  ACTOR_TYPE         STRING,   -- HUMAN | AGENT | SYSTEM | TASK
  ACTOR_ID           STRING,
  EVENT_TS           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  OLD_STATE          STRING,
  NEW_STATE          STRING,
  EVIDENCE_REFERENCE STRING,
  RUN_ID             STRING,
  RATIONALE          STRING,
  PAYLOAD            VARIANT
);

CREATE TABLE IF NOT EXISTS AUDIT.AGENT_RUNS (
  RUN_ID          STRING NOT NULL,
  RUN_TYPE        STRING,   -- CHALLENGER | IMPACT | REASSESS | MINER | AGENT_QA | DEMO
  STARTED_AT      TIMESTAMP_NTZ,
  FINISHED_AT     TIMESTAMP_NTZ,
  STATUS          STRING,
  TRIGGERED_BY    STRING,
  MODEL_NAME      STRING,
  WORKFLOW_VERSION STRING,
  PROMPT_REF      STRING,
  INPUT_SUMMARY   STRING,
  OUTPUT_SUMMARY  STRING,
  EVIDENCE_REFS   VARIANT,
  ERROR_MESSAGE   STRING
);

CREATE TABLE IF NOT EXISTS AUDIT.HUMAN_ACTIONS (
  ACTION_ID     STRING NOT NULL,
  ACTION_TYPE   STRING,   -- CONFIRM_BREACH | DISMISS_CHALLENGE | REQUEST_MORE_EVIDENCE
                          -- | PROPOSE_NEW_ASSUMPTION | APPROVE_NEW_VERSION | REJECT_NEW_VERSION
  OBJECT_TYPE   STRING,
  OBJECT_ID     STRING,
  ACTOR_ID      STRING,
  ACTOR_ROLE    STRING,
  ACTION_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  DECISION      STRING,
  NOTE          STRING,
  PAYLOAD       VARIANT
);

CREATE TABLE IF NOT EXISTS AUDIT.INTEGRATION_ACTIONS (
  INTEGRATION_ACTION_ID STRING NOT NULL,
  TARGET_SYSTEM   STRING,
  ACTION_TYPE     STRING,
  OBJECT_TYPE     STRING,
  OBJECT_ID       STRING,
  EXTERNAL_ID     STRING,
  EXTERNAL_URL    STRING,
  STATUS          STRING,   -- SENT | QUEUED_OUTBOX | FAILED | NOT_CONFIGURED
  REQUEST_PAYLOAD VARIANT,
  RESPONSE_PAYLOAD VARIANT,
  CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  NOTE            STRING
);

-- Central event logger. Used by every procedure in the platform.
CREATE OR REPLACE PROCEDURE AUDIT.LOG_EVENT(
  EVENT_TYPE STRING, OBJECT_TYPE STRING, OBJECT_ID STRING,
  ACTOR_TYPE STRING, ACTOR_ID STRING,
  OLD_STATE STRING, NEW_STATE STRING,
  EVIDENCE_REFERENCE STRING, RUN_ID STRING, RATIONALE STRING, PAYLOAD STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
  EID STRING DEFAULT 'EV-' || REPLACE(UUID_STRING(),'-','');
BEGIN
  INSERT INTO AUDIT.AUDIT_EVENTS
    (EVENT_ID, EVENT_TYPE, OBJECT_TYPE, OBJECT_ID, ACTOR_TYPE, ACTOR_ID,
     EVENT_TS, OLD_STATE, NEW_STATE, EVIDENCE_REFERENCE, RUN_ID, RATIONALE, PAYLOAD)
  SELECT :EID, :EVENT_TYPE, :OBJECT_TYPE, :OBJECT_ID, :ACTOR_TYPE, :ACTOR_ID,
         CURRENT_TIMESTAMP(), :OLD_STATE, :NEW_STATE, :EVIDENCE_REFERENCE, :RUN_ID, :RATIONALE,
         TRY_PARSE_JSON(:PAYLOAD);
  RETURN :EID;
END;
$$;

SELECT 'AUDIT tables ready' AS STATUS;
