-- PremiseFlow :: 08_views.sql
-- Analytical / application views, plus the simplified liquidity balance sheet
-- used by the impact simulator.
-- Hackathon POC - illustrative simplified risk calculations. Not regulatory.

USE DATABASE PREMISEFLOW;
USE SCHEMA CORE;

-- ---------------------------------------------------------------------------
-- Simplified liquidity inputs, derived from the synthetic balance sheet.
-- HQLA is calibrated so that the APPROVED premise (90% retention) yields an
-- LCR of ~118%, which is the number the ALCO decision was taken on.
-- ---------------------------------------------------------------------------
DELETE FROM CORE.LIQUIDITY_INPUTS;
INSERT INTO CORE.LIQUIDITY_INPUTS
 (AS_OF_DATE, HQLA_AMOUNT, RETAIL_STABLE_DEPOSITS, RETAIL_LESS_STABLE_DEPOSITS,
  WHOLESALE_FUNDING, OTHER_OUTFLOWS, EXPECTED_INFLOWS,
  STABLE_RUNOFF_RATE, LESS_STABLE_RUNOFF_RATE, WHOLESALE_RUNOFF_RATE,
  AVG_FUNDING_COST_PCT, REPLACEMENT_FUNDING_SPREAD_BPS, NOTES)
WITH bs AS (
  SELECT d.BALANCE_DATE AS AS_OF_DATE,
         d.GOVERNED_STABLE_DEPOSITS                                   AS RETAIL_STABLE,
         d.TOTAL_DEPOSITS - d.GOVERNED_STABLE_DEPOSITS
           - d.WHOLESALE_LIKE_DEPOSITS                                AS RETAIL_LESS_STABLE,
         d.WHOLESALE_LIKE_DEPOSITS                                    AS WHOLESALE,
         d.TOTAL_DEPOSITS * 0.06                                      AS OTHER_OUT,
         d.TOTAL_DEPOSITS
  FROM CORE.DT_DEPOSIT_DAILY d
  JOIN RAW.V_GEN_CONFIG cfg ON d.BALANCE_DATE = cfg.DEMO_END_DATE
),
calib AS (
  SELECT bs.*,
         0.05 AS STABLE_RR, 0.12 AS LESS_RR, 0.25 AS WHOLESALE_RR,
         RETAIL_STABLE*0.05 + RETAIL_LESS_STABLE*0.12 + WHOLESALE*0.25 + OTHER_OUT AS GROSS_OUT_BASE
  FROM bs
)
SELECT
  AS_OF_DATE,
  -- HQLA pinned so baseline LCR = 118%
  ROUND(1.18 * (GROSS_OUT_BASE - LEAST(GROSS_OUT_BASE*0.35, GROSS_OUT_BASE*0.75)), 2) AS HQLA_AMOUNT,
  ROUND(RETAIL_STABLE,2), ROUND(RETAIL_LESS_STABLE,2), ROUND(WHOLESALE,2),
  ROUND(OTHER_OUT,2), ROUND(GROSS_OUT_BASE*0.35,2),
  STABLE_RR, LESS_RR, WHOLESALE_RR,
  0.0225, 145.0,
  'Synthetic balance sheet as at the demo end date. Runoff rates and the retention '||
  'sensitivity coefficient are illustrative POC parameters, not regulatory calibrations.'
FROM calib;

-- Retention sensitivity coefficient lives alongside as a named parameter.
CREATE TABLE IF NOT EXISTS CORE.SIM_PARAMETERS (PARAM_KEY STRING, PARAM_VALUE FLOAT, DESCRIPTION STRING);
DELETE FROM CORE.SIM_PARAMETERS;
INSERT INTO CORE.SIM_PARAMETERS (PARAM_KEY, PARAM_VALUE, DESCRIPTION)
SELECT * FROM VALUES
 ('RETENTION_RUNOFF_SENSITIVITY', 0.80,
  'Each 1pp of retention shortfall below the approved premise adds 0.80pp to the retail stable runoff rate.'),
 ('INFLOW_CAP_RATIO', 0.75, 'Expected inflows are capped at 75% of gross stressed outflows.'),
 ('BASE_NIM_PCT', 0.0225, 'Illustrative net interest margin applied to total deposits for the NII baseline.'),
 ('APPROVED_RETENTION_REFERENCE', 0.90, 'Approved A-DEP-001 premise used as the runoff calibration anchor.');

-- ---------------------------------------------------------------------------
-- Current state of every assumption: contract + latest observation
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW CORE.V_ASSUMPTION_CURRENT AS
WITH latest_obs AS (
  SELECT o.* FROM CORE.DT_ASSUMPTION_OBSERVATIONS o
  QUALIFY ROW_NUMBER() OVER (PARTITION BY o.ASSUMPTION_ID ORDER BY o.OBSERVATION_DATE DESC) = 1
),
latest_chal AS (
  SELECT c.* FROM CORE.ASSUMPTION_CHALLENGES c
  QUALIFY ROW_NUMBER() OVER (PARTITION BY c.ASSUMPTION_ID ORDER BY c.EVALUATED_AT DESC) = 1
)
SELECT
  a.ASSUMPTION_ID, a.NAME, a.STATEMENT, a.DOMAIN, a.OWNER_ROLE, a.MATERIALITY,
  a.STATUS, a.CURRENT_VERSION, a.METRIC_CODE, a.LAST_VALIDATED_AT,
  v.VERSION_ID, v.VERSION_NUMBER, v.EXPECTED_VALUE, v.LOWER_BOUND, v.UPPER_BOUND,
  v.CHALLENGE_THRESHOLD, v.BREACH_THRESHOLD, v.PERSISTENCE_DAYS, v.DIRECTION,
  v.VALIDITY_ENVELOPE, v.EVIDENCE_SUMMARY, v.APPROVED_BY, v.APPROVED_AT,
  o.OBSERVATION_DATE   AS LATEST_OBSERVATION_DATE,
  o.OBSERVED_VALUE     AS LATEST_OBSERVED_VALUE,
  o.SAMPLE_SIZE        AS LATEST_SAMPLE_SIZE,
  o.OBSERVED_VALUE - v.EXPECTED_VALUE AS DEVIATION,
  CASE WHEN v.EXPECTED_VALUE <> 0
       THEN (o.OBSERVED_VALUE - v.EXPECTED_VALUE) / ABS(v.EXPECTED_VALUE) END AS DEVIATION_PCT,
  ch.CHALLENGE_ID      AS LATEST_CHALLENGE_ID,
  ch.STATUS            AS LATEST_CHALLENGE_STATUS,
  ch.PERSISTENCE_DAYS  AS OBSERVED_PERSISTENCE_DAYS,
  ch.CONFIDENCE        AS LATEST_CONFIDENCE,
  ch.CHANGE_POINT_DATE,
  ch.EXPLANATION       AS LATEST_EXPLANATION,
  (SELECT COUNT(*) FROM CORE.ASSUMPTION_DEPENDENCIES d
    WHERE d.SOURCE_OBJECT = a.ASSUMPTION_ID AND d.VALID_TO IS NULL)      AS DIRECT_DEPENDENCY_COUNT,
  (SELECT COUNT(*) FROM CORE.DECISION_DEPENDENCIES dd
    WHERE dd.ASSUMPTION_ID = a.ASSUMPTION_ID)                            AS DEPENDENT_DECISION_COUNT
FROM CORE.ASSUMPTIONS a
JOIN CORE.ASSUMPTION_VERSIONS v
  ON v.ASSUMPTION_ID = a.ASSUMPTION_ID AND v.IS_CURRENT
LEFT JOIN latest_obs  o ON o.ASSUMPTION_ID = a.ASSUMPTION_ID
LEFT JOIN latest_chal ch ON ch.ASSUMPTION_ID = a.ASSUMPTION_ID;

-- Executive counters
CREATE OR REPLACE VIEW CORE.V_ASSUMPTION_HEALTH AS
SELECT
  COUNT(*)                                             AS ACTIVE_ASSUMPTIONS,
  COUNT_IF(STATUS='VALID')                             AS VALID_COUNT,
  COUNT_IF(STATUS='WATCH')                             AS WATCH_COUNT,
  COUNT_IF(STATUS='CHALLENGED')                         AS CHALLENGED_COUNT,
  COUNT_IF(STATUS='UNDER_REVIEW')                      AS UNDER_REVIEW_COUNT,
  COUNT_IF(STATUS='BREACHED')                          AS BREACHED_COUNT,
  COUNT_IF(STATUS='BREACHED' AND MATERIALITY='CRITICAL') AS CRITICAL_EXPOSURE_COUNT,
  (SELECT COUNT(*) FROM CORE.DECISIONS WHERE GOVERNANCE_STATUS='REASSESSMENT_REQUIRED')
                                                       AS DECISIONS_REQUIRING_REASSESSMENT,
  (SELECT COUNT(*) FROM CORE.REASSESSMENTS WHERE STATUS IN ('OPEN','IN_REVIEW'))
                                                       AS OPEN_REASSESSMENTS
FROM CORE.ASSUMPTIONS
WHERE STATUS <> 'RETIRED';

-- ---------------------------------------------------------------------------
-- The masking view: aggregate looks fine, the governed cohort does not
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW CORE.V_DEPOSIT_MASKING AS
WITH base AS (
  SELECT d.*, cfg.BREAK_DATE, cfg.SPINE_START_DATE, cfg.DEMO_END_DATE,
         FIRST_VALUE(d.TOTAL_DEPOSITS) OVER (ORDER BY d.BALANCE_DATE)            AS TOTAL_AT_START,
         FIRST_VALUE(d.GOVERNED_STABLE_DEPOSITS) OVER (ORDER BY d.BALANCE_DATE)  AS GOVERNED_AT_START
  FROM CORE.DT_DEPOSIT_DAILY d JOIN RAW.V_GEN_CONFIG cfg ON TRUE
)
SELECT
  BALANCE_DATE, BREAK_DATE,
  BALANCE_DATE >= BREAK_DATE                                     AS IS_POST_BREAK,
  TOTAL_DEPOSITS, INCUMBENT_DEPOSITS, NEW_CUSTOMER_DEPOSITS,
  PROMOTIONAL_DEPOSITS, GOVERNED_STABLE_DEPOSITS, TERM_DEPOSITS,
  WHOLESALE_LIKE_DEPOSITS, ACTIVE_CUSTOMERS,
  TOTAL_DEPOSITS / NULLIF(TOTAL_AT_START,0) - 1                  AS TOTAL_DEPOSIT_GROWTH,
  GOVERNED_STABLE_DEPOSITS / NULLIF(GOVERNED_AT_START,0) - 1      AS GOVERNED_DEPOSIT_GROWTH,
  PROMOTIONAL_DEPOSITS / NULLIF(TOTAL_DEPOSITS,0)                 AS PROMOTIONAL_FUNDING_SHARE
FROM base;

CREATE OR REPLACE VIEW CORE.V_RETENTION_BY_DIMENSION AS
SELECT OBSERVATION_DATE, GRAIN, DIM_VALUE, WINDOW_DAYS,
       CURRENT_BALANCE, WINDOW_START_BALANCE, RETENTION_RATE, BALANCE_CHANGE, ACCOUNTS
FROM CORE.DT_RETENTION_DAILY;

-- ---------------------------------------------------------------------------
-- Dependency graph: edges + recursive blast radius
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW CORE.V_DEPENDENCY_EDGES AS
SELECT DEPENDENCY_ID, SOURCE_OBJECT, SOURCE_TYPE, TARGET_OBJECT, TARGET_TYPE,
       RELATIONSHIP_TYPE, MATERIALITY, SENSITIVITY_NOTE
FROM CORE.ASSUMPTION_DEPENDENCIES
WHERE VALID_TO IS NULL;

-- Downstream closure from any node. Depth-capped to stay safe against cycles.
CREATE OR REPLACE VIEW CORE.V_BLAST_RADIUS AS
WITH RECURSIVE walk AS (
  SELECT e.SOURCE_OBJECT AS ROOT_OBJECT, e.SOURCE_OBJECT, e.SOURCE_TYPE,
         e.TARGET_OBJECT, e.TARGET_TYPE, e.RELATIONSHIP_TYPE, e.MATERIALITY,
         e.SENSITIVITY_NOTE, 1 AS DEPTH,
         e.SOURCE_OBJECT||' > '||e.TARGET_OBJECT AS PATH
  FROM CORE.V_DEPENDENCY_EDGES e
  UNION ALL
  SELECT w.ROOT_OBJECT, e.SOURCE_OBJECT, e.SOURCE_TYPE,
         e.TARGET_OBJECT, e.TARGET_TYPE, e.RELATIONSHIP_TYPE, e.MATERIALITY,
         e.SENSITIVITY_NOTE, w.DEPTH + 1,
         w.PATH||' > '||e.TARGET_OBJECT
  FROM walk w
  JOIN CORE.V_DEPENDENCY_EDGES e ON e.SOURCE_OBJECT = w.TARGET_OBJECT
  WHERE w.DEPTH < 6 AND POSITION(e.TARGET_OBJECT, w.PATH) = 0
)
SELECT ROOT_OBJECT, SOURCE_OBJECT, SOURCE_TYPE, TARGET_OBJECT, TARGET_TYPE,
       RELATIONSHIP_TYPE, MATERIALITY, SENSITIVITY_NOTE, DEPTH, PATH
FROM walk;

-- Decisions exposed to an assumption, with the version they relied on
CREATE OR REPLACE VIEW CORE.V_AFFECTED_DECISIONS AS
SELECT
  dd.ASSUMPTION_ID, dd.VERSION_ID AS RELIED_ON_VERSION_ID, dd.RELIANCE_STRENGTH, dd.RELIANCE_NOTE,
  d.DECISION_ID, d.DECISION_REF, d.TITLE, d.COMMITTEE, d.DECISION_DATE,
  d.DECISION_TEXT, d.RATIONALE, d.APPROVED_BY, d.MATERIALITY, d.GOVERNANCE_STATUS,
  d.STATUS_CHANGED_AT, d.SOURCE_DOCUMENT,
  r.REASSESSMENT_ID, r.STATUS AS REASSESSMENT_STATUS, r.TRIGGERED_AT,
  r.IMPACT_SUMMARY, r.AI_RECOMMENDATION
FROM CORE.DECISION_DEPENDENCIES dd
JOIN CORE.DECISIONS d ON d.DECISION_ID = dd.DECISION_ID
LEFT JOIN CORE.REASSESSMENTS r
  ON r.DECISION_ID = dd.DECISION_ID AND r.ASSUMPTION_ID = dd.ASSUMPTION_ID
     AND r.STATUS IN ('OPEN','IN_REVIEW');

-- ---------------------------------------------------------------------------
-- Scenario comparison + audit timeline
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW CORE.V_SCENARIO_COMPARISON AS
SELECT
  s.RUN_ID, s.ASSUMPTION_ID, s.SCENARIO_ID, s.SCENARIO_TYPE, s.NAME AS SCENARIO_NAME,
  s.RETENTION_INPUT, s.CREATED_AT, s.CREATED_BY,
  r.METRIC_ID, r.METRIC_NAME, r.METRIC_VALUE, r.UNIT, r.FORMULA, r.INPUTS,
  r.BREACHES_LIMIT, r.POC_DISCLAIMER,
  m.INTERNAL_LIMIT, m.REGULATORY_MIN
FROM CORE.SCENARIOS s
JOIN CORE.SCENARIO_RESULTS r ON r.SCENARIO_ID = s.SCENARIO_ID
LEFT JOIN CORE.RISK_METRICS m ON m.METRIC_ID = r.METRIC_ID;

CREATE OR REPLACE VIEW AUDIT.V_AUDIT_TIMELINE AS
SELECT
  e.EVENT_ID, e.EVENT_TS, e.EVENT_TYPE, e.OBJECT_TYPE, e.OBJECT_ID,
  e.ACTOR_TYPE, e.ACTOR_ID, e.OLD_STATE, e.NEW_STATE,
  e.EVIDENCE_REFERENCE, e.RUN_ID, e.RATIONALE, e.PAYLOAD,
  CASE e.EVENT_TYPE
    WHEN 'ASSUMPTION_CREATED'        THEN 10
    WHEN 'EVIDENCE_ATTACHED'         THEN 20
    WHEN 'VERSION_APPROVED'          THEN 30
    WHEN 'OBSERVATION_GENERATED'     THEN 40
    WHEN 'CHALLENGE_DETECTED'        THEN 50
    WHEN 'BREACH_DETECTED'           THEN 60
    WHEN 'BREACH_CONFIRMED'          THEN 70
    WHEN 'IMPACT_SIMULATED'          THEN 80
    WHEN 'DECISION_REOPENED'         THEN 90
    WHEN 'NEW_VERSION_PROPOSED'      THEN 100
    WHEN 'NEW_VERSION_APPROVED'      THEN 110
    ELSE 999 END AS STAGE_ORDER
FROM AUDIT.AUDIT_EVENTS e;

SELECT 'views ready' AS STATUS,
  (SELECT COUNT(*) FROM CORE.V_ASSUMPTION_CURRENT) AS ASSUMPTIONS,
  (SELECT COUNT(*) FROM CORE.V_BLAST_RADIUS WHERE ROOT_OBJECT='A-DEP-001') AS ADEP001_BLAST_EDGES,
  (SELECT ROUND(HQLA_AMOUNT/1e6,2) FROM CORE.LIQUIDITY_INPUTS) AS HQLA_M,
  (SELECT ROUND(RETAIL_STABLE_DEPOSITS/1e6,2) FROM CORE.LIQUIDITY_INPUTS) AS RETAIL_STABLE_M;
