-- PremiseFlow :: 14_grants.sql
-- Least-privilege application roles.
--
-- Three roles, matching the governance model:
--   PREMISEFLOW_VIEWER    read-only; can see everything, change nothing
--   PREMISEFLOW_ANALYST   viewer + may run detection, narration and simulation
--   PREMISEFLOW_APPROVER  analyst + may confirm breaches and approve versions
--
-- The split is enforced twice: by these grants, and independently by
-- APP.IS_HUMAN_ACTOR inside the governed procedures. Granting a procedure to a
-- role never lets an AI actor through the actor guard.

USE DATABASE PREMISEFLOW;

CREATE ROLE IF NOT EXISTS PREMISEFLOW_VIEWER   COMMENT='PremiseFlow read-only';
CREATE ROLE IF NOT EXISTS PREMISEFLOW_ANALYST  COMMENT='PremiseFlow analyst: detect, explain, simulate';
CREATE ROLE IF NOT EXISTS PREMISEFLOW_APPROVER COMMENT='PremiseFlow governance owner: confirm and approve';

GRANT ROLE PREMISEFLOW_VIEWER  TO ROLE PREMISEFLOW_ANALYST;
GRANT ROLE PREMISEFLOW_ANALYST TO ROLE PREMISEFLOW_APPROVER;

-- ---- compute + database visibility ---------------------------------------
GRANT USAGE ON WAREHOUSE PREMISEFLOW_WH TO ROLE PREMISEFLOW_VIEWER;
GRANT USAGE ON DATABASE PREMISEFLOW      TO ROLE PREMISEFLOW_VIEWER;
GRANT USAGE ON SCHEMA PREMISEFLOW.CORE   TO ROLE PREMISEFLOW_VIEWER;
GRANT USAGE ON SCHEMA PREMISEFLOW.RAW    TO ROLE PREMISEFLOW_VIEWER;
GRANT USAGE ON SCHEMA PREMISEFLOW.AI     TO ROLE PREMISEFLOW_VIEWER;
GRANT USAGE ON SCHEMA PREMISEFLOW.APP    TO ROLE PREMISEFLOW_VIEWER;
GRANT USAGE ON SCHEMA PREMISEFLOW.AUDIT  TO ROLE PREMISEFLOW_VIEWER;

-- ---- read access ----------------------------------------------------------
GRANT SELECT ON ALL TABLES IN SCHEMA PREMISEFLOW.CORE  TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA PREMISEFLOW.RAW   TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA PREMISEFLOW.AI    TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA PREMISEFLOW.AUDIT TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PREMISEFLOW.CORE  TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PREMISEFLOW.AUDIT TO ROLE PREMISEFLOW_VIEWER;

GRANT SELECT ON ALL VIEWS IN SCHEMA PREMISEFLOW.CORE  TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PREMISEFLOW.RAW   TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PREMISEFLOW.AI    TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PREMISEFLOW.AUDIT TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PREMISEFLOW.CORE  TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PREMISEFLOW.AUDIT TO ROLE PREMISEFLOW_VIEWER;

GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA PREMISEFLOW.CORE TO ROLE PREMISEFLOW_VIEWER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA PREMISEFLOW.CORE TO ROLE PREMISEFLOW_VIEWER;

GRANT SELECT ON SEMANTIC VIEW PREMISEFLOW.AI.PREMISEFLOW_SEMANTIC TO ROLE PREMISEFLOW_VIEWER;
GRANT USAGE ON CORTEX SEARCH SERVICE PREMISEFLOW.AI.PREMISEFLOW_DOC_SEARCH TO ROLE PREMISEFLOW_VIEWER;
GRANT USAGE ON AGENT PREMISEFLOW.AI.PREMISEFLOW_AGENT TO ROLE PREMISEFLOW_VIEWER;
GRANT READ ON STAGE PREMISEFLOW.AI.DOCS TO ROLE PREMISEFLOW_VIEWER;
GRANT USAGE ON STREAMLIT PREMISEFLOW.APP.PREMISEFLOW_APP TO ROLE PREMISEFLOW_VIEWER;

-- ---- analyst: detection, narration, simulation, Q&A ----------------------
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.RUN_CHALLENGER(STRING, STRING, DATE)            TO ROLE PREMISEFLOW_ANALYST;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.EXPLAIN_CHALLENGE(STRING, STRING)                TO ROLE PREMISEFLOW_ANALYST;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.RUN_IMPACT_FOR_ASSUMPTION(STRING, STRING)        TO ROLE PREMISEFLOW_ANALYST;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.RUN_IMPACT_SIMULATION(STRING, FLOAT, STRING, STRING, STRING, STRING) TO ROLE PREMISEFLOW_ANALYST;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.ASK_PREMISEFLOW(STRING, STRING)                  TO ROLE PREMISEFLOW_ANALYST;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.PROPOSE_NEW_VERSION(STRING, STRING, FLOAT, FLOAT, FLOAT, FLOAT, FLOAT, FLOAT, STRING, STRING, STRING) TO ROLE PREMISEFLOW_ANALYST;
GRANT USAGE ON FUNCTION PREMISEFLOW.APP.IS_HUMAN_ACTOR(STRING, STRING)                    TO ROLE PREMISEFLOW_VIEWER;

-- ---- approver: the reserved governance actions ---------------------------
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.CONFIRM_BREACH(STRING, STRING, STRING, STRING, STRING)        TO ROLE PREMISEFLOW_APPROVER;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.DISMISS_CHALLENGE(STRING, STRING, STRING, STRING, STRING)      TO ROLE PREMISEFLOW_APPROVER;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.REQUEST_MORE_EVIDENCE(STRING, STRING, STRING, STRING, STRING)  TO ROLE PREMISEFLOW_APPROVER;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.APPROVE_NEW_VERSION(STRING, STRING, STRING, STRING, STRING)    TO ROLE PREMISEFLOW_APPROVER;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.REJECT_NEW_VERSION(STRING, STRING, STRING, STRING, STRING)     TO ROLE PREMISEFLOW_APPROVER;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.RESOLVE_REASSESSMENT(STRING, STRING, STRING, STRING, STRING, STRING) TO ROLE PREMISEFLOW_APPROVER;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.RESET_DEMO()                                     TO ROLE PREMISEFLOW_APPROVER;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.RUN_DEMO(STRING)                                 TO ROLE PREMISEFLOW_APPROVER;
GRANT USAGE ON PROCEDURE PREMISEFLOW.APP.MONITORING_CYCLE()                               TO ROLE PREMISEFLOW_APPROVER;

-- Writes required by the governed procedures when run with caller's rights.
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PREMISEFLOW.CORE  TO ROLE PREMISEFLOW_APPROVER;
GRANT INSERT ON ALL TABLES IN SCHEMA PREMISEFLOW.AUDIT                 TO ROLE PREMISEFLOW_APPROVER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA PREMISEFLOW.AUDIT         TO ROLE PREMISEFLOW_APPROVER;

-- The build role keeps ownership; hand the approver role to a named human.
GRANT ROLE PREMISEFLOW_APPROVER TO ROLE ACCOUNTADMIN;

SHOW ROLES LIKE 'PREMISEFLOW%';
