-- PremiseFlow :: tests/demo/replay.sql
-- Reproducible end-to-end demo replay, then verification that it landed.

USE WAREHOUSE PREMISEFLOW_WH;

-- 1. Back to the approved baseline. Audit history is deliberately preserved.
CALL PREMISEFLOW.APP.RESET_DEMO();

SELECT (SELECT COUNT_IF(STATUS='VALID') FROM PREMISEFLOW.CORE.ASSUMPTIONS)              AS VALID_ASSUMPTIONS,
       (SELECT COUNT_IF(GOVERNANCE_STATUS='APPROVED') FROM PREMISEFLOW.CORE.DECISIONS)  AS APPROVED_DECISIONS,
       (SELECT COUNT(*) FROM PREMISEFLOW.CORE.REASSESSMENTS)                            AS REASSESSMENTS,
       (SELECT COUNT(*) FROM PREMISEFLOW.CORE.ASSUMPTION_CHALLENGES)                    AS CHALLENGES,
       (SELECT COUNT(*) FROM PREMISEFLOW.AUDIT.AUDIT_EVENTS)                            AS AUDIT_PRESERVED;
-- expect: 10 valid, 4 approved, 0 reassessments, 0 challenges, audit > 0

-- 2. Advance the scenario. Returns eight narrated stages.
CALL PREMISEFLOW.APP.RUN_DEMO('manikant.kella');

-- 3. The progression, as three recorded challenges rather than an assertion.
SELECT OBSERVATION_DATE, STATUS, ROUND(OBSERVED_VALUE,4) AS OBSERVED,
       EXPECTED_VALUE AS APPROVED, PERSISTENCE_DAYS, CHANGE_POINT_DATE,
       ROUND(CONFIDENCE,3) AS CONFIDENCE
FROM PREMISEFLOW.CORE.ASSUMPTION_CHALLENGES
WHERE ASSUMPTION_ID = 'A-DEP-001'
ORDER BY EVALUATED_AT;
-- expect: VALID ~0.92, then CHALLENGED ~0.87, then BREACHED ~0.78

-- 4. Impact
SELECT SCENARIO_TYPE, ROUND(RETENTION_INPUT,4) AS RETENTION, METRIC_ID,
       ROUND(METRIC_VALUE,2) AS VALUE, UNIT, BREACHES_LIMIT
FROM PREMISEFLOW.CORE.V_SCENARIO_COMPARISON
WHERE ASSUMPTION_ID='A-DEP-001' AND METRIC_ID IN ('LCR','FUNDING_GAP_90D','NII_12M')
QUALIFY ROW_NUMBER() OVER (PARTITION BY SCENARIO_TYPE, METRIC_ID ORDER BY CREATED_AT DESC)=1
ORDER BY METRIC_ID, SCENARIO_TYPE;
-- expect: LCR 118 baseline vs ~98 observed (BREACHES_LIMIT true)

-- 5. Consequence: two decisions reopened, two untouched
SELECT DECISION_REF, TITLE, GOVERNANCE_STATUS FROM PREMISEFLOW.CORE.DECISIONS
ORDER BY DECISION_REF;

-- 6. The cohort that caused it
SELECT GRAIN, DIM_VALUE, ROUND(RETENTION_RATE,4) AS RETENTION, ACCOUNTS
FROM PREMISEFLOW.CORE.DT_RETENTION_DAILY
WHERE OBSERVATION_DATE = (SELECT MAX(OBSERVATION_DATE) FROM PREMISEFLOW.CORE.DT_RETENTION_DAILY)
ORDER BY GRAIN, RETENTION_RATE;

-- 7. The lifecycle, evidenced
SELECT EVENT_TYPE, ACTOR_TYPE, COUNT(*) AS EVENTS, MIN(EVENT_TS) AS FIRST_SEEN
FROM PREMISEFLOW.AUDIT.AUDIT_EVENTS
WHERE EVENT_TYPE IN ('CHALLENGE_DETECTED','BREACH_DETECTED','AI_EXPLANATION_GENERATED',
                     'BREACH_CONFIRMED','IMPACT_SIMULATED','DECISION_REOPENED')
GROUP BY 1,2 ORDER BY FIRST_SEEN;

-- 8. External actions that would have been raised
SELECT TARGET_SYSTEM, ACTION_TYPE, STATUS, DEDUPE_KEY FROM PREMISEFLOW.CORE.ACTION_OUTBOX
ORDER BY TARGET_SYSTEM, DEDUPE_KEY;
